// colors  '#000', '#d1d5db','#b18ed6', '#EB1D36', '#EE6983' ,'#42855B', '#277BC0', '#FEDB39'

export const singleProduct = [
  {
    name: 'PlayStation 5',
    category: 'Gaming Consoles',
    price: 60000,
    description:
      'Appropriately promote quality initiatives rather than low-risk high-yield e-markets. Credibly expedite impactful catalysts for change through top-line scenarios. Distinctively enhance progressive process improvements after open-source initiatives. Compellingly matrix long-term high-impact strategic.',
    stock: 3,
    stars: 5,
    reviews: 50,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Sony',
    images: [
      'https://i.ibb.co/0MP2BCL/playstation-5.jpg',
      'https://i.ibb.co/tq1NwvF/ps5.webp',
      'https://i.ibb.co/g4P7rvX/ps5.webp',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'PlayStation 4',
    category: 'Gaming Consoles',
    price: 43000,
    description:
      'Incredible games & non-stop entertainment. The PS4 console, delivering awesome gaming power, incredible entertainment and vibrant HDR technology. Store your games, apps, screenshots and videos with up to 1TB storage inside the PS4 console – slimmer and lighter than the original PS4 model and available in Jet Black and more colours. Catch up with old friends at an affordable price. Some of the most iconic games of a generation are waiting for you in the PlayStation Hits range, including PlayStation exclusives, blockbuster hits and acclaimed games you may have missed.',
    stock: 20,
    stars: 4.8,
    reviews: 1000,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Sony',
    images: [
      'https://i.ibb.co/r7cphgt/ps4.jpg',
      'https://i.ibb.co/3pv7xh8/ps-1.jpg',
      'https://i.ibb.co/Cmnstr5/ps-2.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Xbox Series X',
    category: 'Gaming Consoles',
    price: 49900,
    description:
      'Introducing Xbox Series X, the fastest, most powerful Xbox ever. Play thousands of titles from four generations of consoles—all games look and play best on Xbox Series X. At the heart of Series X is the Xbox Velocity Architecture, which pairs a custom SSD with integrated software for faster, streamlined gameplay with significantly reduced load times. Seamlessly move between multiple games in a flash with Quick Resume. Explore rich new worlds and enjoy the action like never before with the unmatched 12 teraflops of raw graphic processing power. Enjoy 4K gaming at up to 120 frames per second, advanced 3D spatial sound, and more. Get started with Xbox Game Pass Ultimate, which includes a library of 100+ high-quality games, an EA Play membership, online multiplayer, and all new Xbox Game Studios titles the day they launch like Halo Infinite (membership sold separately). Xbox Smart delivery ensures you play the best available version of your game no matter which Console you are playing on.',
    stock: 10,
    stars: 4,
    reviews: 300,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Microsoft',
    images: [
      'https://i.ibb.co/mXbLHYg/series-x.jpg',
      'https://i.ibb.co/nnpNWDc/xbox.jpg',
      'https://i.ibb.co/nn7vHQ1/xbox.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Xbox Series S',
    category: 'Gaming Consoles',
    price: 41400,
    description:
      'Introducing Xbox Series S, the smallest, sleekest Xbox ever. At 60% smaller than Xbox Series X, it delivers the speed and performance of a next-gen, all-digital console at an accessible price point. Limit 1 console purchase per customer.Xbox Series S is available as a bundle. Bundle and score an Xbox Series S now, plus an option to add Xbox Game Pass Ultimate 3 Month Membership, select controllers and Microsoft Complete for Xbox.',
    stock: 7,
    stars: 4.2,
    reviews: 150,
    id: 'sf5sd4f5s454sdf',
    colors: ['#d1d5db'],
    company: 'Microsoft',
    images: [
      'https://i.ibb.co/P1Rz8Vg/series-s.jpg',
      'https://i.ibb.co/CJd6YHQ/series-s.jpg',
      'https://i.ibb.co/nn7vHQ1/xbox.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Nintendo Switch',
    category: 'Gaming Consoles',
    price: 30000,
    description:
      'Get the gaming system that lets you play the games you want, wherever you are, however you like. Includes the Nintendo Switch console and Nintendo Switch dock in black, with contrasting left and right JoyCon controllers-one red, one blue. Also includes all the extras you need to get started. Model number: HAC-001(-01) (product serial number begins with “XKW”) This model includes battery life of approximately 4.5 - 9 hours . The battery life will depend on the games you play. For instance, the battery will last approximately 5.5 hours for The Legend of Zelda: Breath of the Wild (games sold separately). Introducing Nintendo Switch, the new home video game system from Nintendo. In addition to providing single and multiplayer thrills at home, the Nintendo Switch system can be taken on the go so players can enjoy a full home console experience anytime, anywhere. The mobility of a handheld is now added to the power of a home gaming system, with unprecedented new play styles brought to life by the two new Joy-Con controllers.',
    stock: 50,
    stars: 4.5,
    reviews: 500,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#277BC0', '#EB1D36'],
    company: 'Nintendo',
    images: [
      'https://i.ibb.co/zNVq8sp/nintendo-switch.jpg',
      'https://i.ibb.co/TTyStfd/nswitch.jpg',
      'https://i.ibb.co/2dYJzLY/Switch.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Nintendo Switch OLED',
    category: 'Gaming Consoles',
    price: 35000,
    description:
      'Meet the newest member of the Nintendo Switch family. The new system features a vibrant 7-inch OLED screen, a wide adjustable stand, a dock with a wired LAN port, 64 GB of internal storage, and enhanced audio.Play anytime, anywhere, with anyone. Nintendo Switch can transform to suit your situation, so you can play the games you want, no matter how busy life may be.Pick it up and play with the Joy-Con controllers attached. Nintendo Switch (OLED model) includes a vibrant 7-inch OLED screen with a slimmer bezel. The large screens vivid colours and high contrast deliver a rich handheld and tabletop gaming experience, bringing games to life whether youre racing at top speed or squaring off against enemies.Flip out the stand and hand a controller to another player to share the screen and enjoy competitive or co-operative multiplayer, anytime and anywhere. Nintendo Switch (OLED model)s wide adjustable stand can be set to your preferred viewing angle for comfortable gameplay in tabletop mode.',
    stock: 30,
    stars: 4.6,
    reviews: 100,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Nintendo',
    images: [
      'https://i.ibb.co/j6KNjbQ/nintendo-switch-oled.jpg',
      'https://i.ibb.co/N1NKwgy/oled-2.jpg',
      'https://i.ibb.co/f0KLwSd/oled-1.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Steam Deck',
    category: 'Gaming Consoles',
    price: 39900,
    description:
      'Valve has positioned the Steam Deck as a gaming laptop that you can hold like a Switch, and for how small it is, its packing some serious power. All versions of the Steam Deck utilize a high-speed SSD of some kind. The entry-level model uses 64GB eMMC and the two pricier editions have an M.2 2230 NVMe SSD. Because of the ultra-compact form factor of the handheld, Valve has said that the Steam Deck SSD shouldnt be replaced due to the way that the memory has been connected to the unit; while it can technically be done, the company is heavily discouraging users from doing so - at least right now. You can use the Steam Deck like a PC and dock it like a Switch',
    stock: 10,
    stars: 4,
    reviews: 20,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Valve',
    images: [
      'https://i.ibb.co/ykgNs1s/steam-deck.jpg',
      'https://i.ibb.co/y61d7zh/steam-deck.jpg',
      'https://i.ibb.co/WH5pkLs/steam-deck.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  //TODO: CONTROLLERS
  {
    name: 'PS5 CONTROLLER',
    category: 'Controllers',
    price: 6900,
    description:
      'PS5 Controller Charging Station for Playstation 5 Dualsense Controller with Dual Stand Charger Dock, Upgrade PS5 Controller Charger Accessories Incl. Fast Charging Cable, PS5 Charging Station White This PS5 controller charger stand has 4 anti-slip rubber which keep the PS5 wireless charger in place and charge up double PS5 controllers simultaneously in the sony PS5 controller charger dock when not playing games, and it doesnt take up much room, ideal charging base for your PS5 controllers',
    stock: 30,
    stars: 5,
    reviews: 30,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#b18ed6', '#d1d5db', '#EE6983', '#EB1D36', '#277BC0'],
    company: 'Sony',
    images: [
      'https://i.ibb.co/yNsG8sb/ps5-controller.jpg',
      'https://i.ibb.co/f8DNgW2/kamil-s-K-Qbvo-Nq-Rvo-unsplash.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'PS4 CONTROLLER',
    category: 'Controllers',
    price: 5900,
    description:
      'Precision Controller for PlayStation 4: The feel, shape, and sensitivity of the DualShock 4’s analog sticks and trigger buttons have been enhanced to offer players absolute control for all games. Sharing at your Fingertips: The addition of the Share button makes sharing your greatest gaming moments as easy as a push of a button. Upload gameplay videos and screenshots directly from your system or live-stream your gameplay, all without disturbing the game in progress.New ways to Play: Revolutionary features like the touch pad, integrated light bar, and built-in speaker offer exciting new ways to experience and interact with your games and its 3.5mm audio jack offers a practical personal audio solution for gamers who want to listen to their games in private.',
    stock: 100,
    stars: 4.7,
    reviews: 200,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#b18ed6', '#d1d5db', '#EE6983', '#EB1D36', '#277BC0'],
    company: 'Sony',
    images: [
      'https://i.ibb.co/zZb8dj5/ps4-controller-2.jpg',
      'https://i.ibb.co/g6fGySn/charindra-salgado-8-Kz-AAf4-GKuk-unsplash.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'PS4 CONTROLLER LIMITED ED',
    category: 'Controllers',
    price: 6900,
    description:
      'Precision Controller for PlayStation 4: The feel, shape, and sensitivity of the DualShock 4’s analog sticks and trigger buttons have been enhanced to offer players absolute control for all games. Sharing at your Fingertips: The addition of the Share button makes sharing your greatest gaming moments as easy as a push of a button. Upload gameplay videos and screenshots directly from your system or live-stream your gameplay, all without disturbing the game in progress.New ways to Play: Revolutionary features like the touch pad, integrated light bar, and built-in speaker offer exciting new ways to experience and interact with your games and its 3.5mm audio jack offers a practical personal audio solution for gamers who want to listen to their games in private.',
    stock: 5,
    stars: 4.9,
    reviews: 10,
    id: 'sf5sd4f5s454sdf',
    colors: ['#d1d5db', '#42855B', '#FEDB39'],
    company: 'Sony',
    images: [
      'https://i.ibb.co/YkzxkSH/ps4-controller-3.jpg',
      'https://i.ibb.co/QDzpPhF/mike-meyers-IJy-Xoy-Gmi-ZY-unsplash.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'XBOX CONTROLLER ',
    category: 'Controllers',
    price: 4900,
    description:
      'Experience the modernized design of the Xbox Wireless Controller in Carbon Black, featuring sculpted surfaces and refined geometry for enhanced comfort and effortless control during gameplay with battery usage up to 40 hours.Stay on target with the hybrid D-pad, textured grip on the triggers, bumpers, and back-case. Plug in any compatible headset with the 3.5mm audio headset jack. Connect using the USB-C port for direct plug and play to console or PC. Support for AA batteries is included on the rear.Seamlessly capture and share content with the Share button.Use Xbox Wireless or Bluetooth to play across Xbox Series X|S, Xbox One, and Windows 10/11 devices.Compatible with Xbox Series X|S, Xbox One, and Windows 10/11 devices.',
    stock: 30,
    stars: 4.4,
    reviews: 100,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db', '#EB1D36', '#EE6983', '#277BC0', '#FEDB39'],
    company: 'Microsoft',
    images: [
      'https://i.ibb.co/YQvJrdv/xbox-controller-2.jpg',
      'https://i.ibb.co/HdrbXQB/xbox-controller.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'NINTENDO SWITCH JOYCON ',
    category: 'Controllers',
    price: 7900,
    description:
      '2 Joy Con can be used independently in each hand, or together as 1 game controller when attached to the Joy Con gri. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule In this stunning Open Air Adventure. Number of Players: 1 player.Each Joy Con has a full set of buttons and can act as a standalone controller, and each includes an accelerometer and gyro sensor, making independent left and right motion control possible',
    stock: 20,
    stars: 4.6,
    reviews: 150,
    id: 'sf5sd4f5s454sdf',
    colors: ['#EB1D36', '#277BC0'],
    company: 'Nintendo',
    images: [
      'https://i.ibb.co/XXnZm2m/sara-kurfess-jqp-RECmi-NEU-unsplash.jpg',
      'https://i.ibb.co/8rzf4MP/switch-joycon-1.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'NINTENDO SWITCH JOYCON SPECIAL ED',
    category: 'Controllers',
    price: 7900,
    description:
      '2 Joy Con can be used independently in each hand, or together as 1 game controller when attached to the Joy Con gri. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule In this stunning Open Air Adventure. Number of Players: 1 player.Each Joy Con has a full set of buttons and can act as a standalone controller, and each includes an accelerometer and gyro sensor, making independent left and right motion control possible',
    stock: 4,
    stars: 4.8,
    reviews: 13,
    id: 'sf5sd4f5s454sdf',
    colors: ['#EE6983', '#42855B', '#FEDB39'],
    company: 'Nintendo',
    images: [
      'https://i.ibb.co/5691T0q/switch-joycon-2.jpg',
      'https://i.ibb.co/B3mykX8/joycon.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: '8BITDO PRO FOR NINTENDO SWITCH',
    category: 'Controllers',
    price: 4500,
    description:
      'Compatible with Switch, PC, macOS, Android, Steam and Raspberry Pi.Fully featured Controller- clickable joysticks, rumble vibration, motion controls, wireless Bluetooth, rechargeable battery, home and screenshot Buttons and a USB-C connector! Perfect classic d-pad',
    stock: 8,
    stars: 4.7,
    reviews: 26,
    id: 'sf5sd4f5s454sdf',
    colors: ['##d1d5db'],
    company: '8BitDo',
    images: [
      'https://i.ibb.co/ZMn4Lmt/ravi-palwe-Vrw58w-U4a-I-unsplash.jpg',
      'https://i.ibb.co/M91HFGV/8bitdo.jpg',
      'https://i.ibb.co/fkBR5L7/random-controller.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  //TODO HEADPHONES
  {
    name: 'APPLE WIRED EARPODS',
    category: 'Headphones',
    price: 2900,
    description:
      'Unlike traditional, circular earbuds, the design of the EarPods is defined by the geometry of the ear which makes them more comfortable for more people than any other earbud-style headphones. The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. The EarPods with lightning connector also include a built-in remote that lets you adjust the volume, control the playback of music and video, and answer or end calls with a pinch of the cord. Works with all devices that have a lightning connector and support iOS 10 or later, including iPod touch, iPad, and iPhone',
    stock: 12,
    stars: 4.2,
    reviews: 65,
    id: 'sf5sd4f5s454sdf',
    colors: ['##d1d5db'],
    company: 'Apple',
    images: [
      'https://i.ibb.co/Xtw6v5W/kiran-ck-i1-Ex8-ENX3r-I-unsplash.jpg',
      'https://i.ibb.co/JsprY6m/AIRPODS.jpg',
      'https://i.ibb.co/fp0N9N8/RANDOM.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'BEATS WIRELESS HEADPHONES',
    category: 'Headphones',
    price: 7900,
    description:
      'Beats EP wired on-ear headphone in blue delivers masterfully tuned sound.Durable, lightweight design reinforced with stainless steel Take calls and control music on your iOS and Android devices with the microphone in the RemoteTalk cable,Battery free for unlimited playback Adjustable vertical sliders for a personalized fit',
    stock: 4,
    stars: 4.8,
    reviews: 8,
    id: 'sf5sd4f5s454sdf',
    colors: ['##d1d5db'],
    company: 'Beats',
    images: [
      'https://i.ibb.co/ykFgK4N/BEATS-1.jpg',
      'https://i.ibb.co/gJxqnV1/BEATS-2.jpg',
      'https://i.ibb.co/j87wXbM/HEADPHONES.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'BEATS LIMITED HEADPHONES',
    category: 'Headphones',
    price: 8900,
    description:
      'Beats EP wired on-ear headphone in blue delivers masterfully tuned sound.Durable, lightweight design reinforced with stainless steel Take calls and control music on your iOS and Android devices with the microphone in the RemoteTalk cable,Battery free for unlimited playback Adjustable vertical sliders for a personalized fit',
    stock: 2,
    stars: 4.9,
    reviews: 8,
    id: 'sf5sd4f5s454sdf',
    colors: ['#EE6983', '#b18ed6'],
    company: 'Beats',
    images: [
      'https://i.ibb.co/TtkbtfR/alexunder-hess-b-WZAPKm0z-ZE-unsplash.jpg',
      'https://i.ibb.co/x5rys15/ervo-rocks-Zam8-Tv-Eg-N5o-unsplash.jpg',
      'https://i.ibb.co/j87wXbM/HEADPHONES.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'TWS EARPHONES',
    category: 'Headphones',
    price: 2900,
    description:
      '[Bluetooth 5.0 technology]The Bluetooth earbuds adopt Bluetooth 5.0 technology providing a more stable connection (connection distance up to 32ft), faster paring, and universal compatibility.[Wireless charging support] These K6 wireless Headphones support both wireless charging and USB C cable charging.[LED Light shows] These audifonos Bluetooth inalambricos have an LED display on the charging case to show the battery power. You can read it out easily and clearly. The charging case could provide full charges to the earbuds 3~4 times, and the calling could last 4~5 hours after a single charge; music playing could last 5~6hours. Therefore, you can enjoy 30 hours of music play at the most by taking turns with these Bluetooth Ear buds.',
    stock: 9,
    stars: 4.4,
    reviews: 2,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'TWS',
    images: [
      'https://i.ibb.co/GTyCqVH/ignacio-r-3yr-JSb2f-MT0-unsplash.jpg',
      'https://i.ibb.co/7rc1sJW/EARPHONES.jpg',
      'https://i.ibb.co/j87wXbM/HEADPHONES.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'QCY HEADPHONES',
    category: 'Headphones',
    price: 1900,
    description:
      '[Bluetooth 5.0 technology]The Bluetooth earbuds adopt Bluetooth 5.0 technology providing a more stable connection (connection distance up to 32ft), faster paring, and universal compatibility.[Wireless charging support] These K6 wireless Headphones support both wireless charging and USB C cable charging.[LED Light shows] These audifonos Bluetooth inalambricos have an LED display on the charging case to show the battery power. You can read it out easily and clearly. The charging case could provide full charges to the earbuds 3~4 times, and the calling could last 4~5 hours after a single charge; music playing could last 5~6hours. Therefore, you can enjoy 30 hours of music play at the most by taking turns with these Bluetooth Ear buds.',
    stock: 14,
    stars: 3.8,
    reviews: 5,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#EB1D36'],
    company: 'QCY',
    images: [
      'https://i.ibb.co/dkMBFfN/luke-peterson-l-UMj2-Zv5-HUE-unsplash.jpg',
      'https://i.ibb.co/dLq3zqC/lee-campbell-GI6-L2pki-Zg-Q-unsplash.jpg',
      'https://i.ibb.co/j87wXbM/HEADPHONES.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'TREBLUB HEADPHONES',
    category: 'Headphones',
    price: 1500,
    description:
      '[Bluetooth 5.0 technology]The Bluetooth earbuds adopt Bluetooth 5.0 technology providing a more stable connection (connection distance up to 32ft), faster paring, and universal compatibility.[Wireless charging support] These K6 wireless Headphones support both wireless charging and USB C cable charging.[LED Light shows] These audifonos Bluetooth inalambricos have an LED display on the charging case to show the battery power. You can read it out easily and clearly. The charging case could provide full charges to the earbuds 3~4 times, and the calling could last 4~5 hours after a single charge; music playing could last 5~6hours. Therefore, you can enjoy 30 hours of music play at the most by taking turns with these Bluetooth Ear buds.',
    stock: 14,
    stars: 3.8,
    reviews: 5,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#EB1D36'],
    company: 'TREBLUB',
    images: [
      'https://i.ibb.co/7tPVnk1/yogendra-singh-fr6-Sj-LC7o1-Y-unsplash.jpg',
      'https://i.ibb.co/3mMwF0j/yarenci-hdz-Tt-TIh-Vp-Yo-M-unsplash.jpg',
      'https://i.ibb.co/j87wXbM/HEADPHONES.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  //TODO MONITORS
  {
    name: 'APPLE 24inch Pro Display',
    category: 'Monitors',
    price: 399900,
    description:
      '24-inch LCD display with Retina 6K resolution (6016 by 3384 pixels). Pro Stand and VESA Mount Adapter sold separately Extreme Dynamic Range (XDR) Brightness: 1000 nits sustained, 1600 nits peak Contrast ratio: 1,000,000:1 P3 wide color gamut, 10-bit color depth Superwide viewing angle',
    stock: 1,
    stars: 5,
    reviews: 3,
    id: 'sf5sd4f5s454sdf',
    colors: ['#d1d5db'],
    company: 'Apple',
    images: [
      'https://i.ibb.co/BscSMw7/quaritsch-photography-m2zu-B8-Dqwy-M-unsplash.jpg',
      'https://i.ibb.co/2PPpXQf/nicolas-gonzalez-183-F-v-Na-N8-A-unsplash.jpg',
      'https://i.ibb.co/bFwX4d6/alienware-Hpaq-k-Bc-YHk-unsplash.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'SAMSUNG 32inch Ultrawide Display',
    category: 'Monitors',
    price: 479995,
    description:
      'First Curved monitor with Intel Thunderbolt 3 for single-source power and charging. One cable to Link and dock monitor and laptop. Tbt3 offers 40 Gaps processing speed - - 4x faster than USB - - and up to 85W laptop charging. Connectivity available for docks, displays and peripherals including Macs, USB Type-C laptops. storage drives and external Graphics cards. Ultra wide WQHD resolution 3440 x 1440. Great multi-tasking with intuitive screen split software PBP/PIP. Qled technology provides a wide range of colors, darker blacks with a 3000: 1 contrast ratio',
    stock: 1,
    stars: 0,
    reviews: 0,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Samsung',
    images: [
      'https://i.ibb.co/X39TMRN/alexandru-acea-rm-HTCPXUk9g-unsplash.jpg',
      'https://i.ibb.co/cLDq7Rw/karl-pawlowicz-QUHuwy-Ng-SA0-unsplash.jpg',
      'https://i.ibb.co/bFwX4d6/alienware-Hpaq-k-Bc-YHk-unsplash.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Dell 24inch Monitor',
    category: 'Monitors',
    price: 4899,
    description:
      'Dell P2421D 24 Inch 1440p QHD, IPS Thin Bezel Monitor, HDMI, DisplayPort, VESA Certified, Black QHD 2560 X 1440 Resolution. 8ms Response Time. Flexible, all-day comfort: Pivot, tilt, swivel and adjust the height of your monitor fo. comfortable setup all day long. Or choose from a variety of mounts and stands, including VESA, . even more flexibility. In-Plane Switching Technology',
    stock: 17,
    stars: 4.6,
    reviews: 16,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Dell',
    images: [
      'https://i.ibb.co/HTGKCm7/kitai-jogia-zhvaeh-R9r-A-unsplash.jpg',
      'https://i.ibb.co/VD8yDPh/guglielmo-basile-ikz8-R6-LGb-K8-unsplash.jpg',
      'https://i.ibb.co/bFwX4d6/alienware-Hpaq-k-Bc-YHk-unsplash.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'LG 24inch Monitor',
    category: 'Monitors',
    price: 19999,
    description:
      'LG 24MP88HV-S Neo Blade III Monitor 24" FHD (1920 x 1080) IPS Display, 2.5mm Ultra-Slim Bezel, sRGB over 99%, On-Screen Control with Screen Split 2.0 Full HD IPS Monitor. Infinity Display (2.5 millimeter bezel); OS Compatibility Windows 10. SRGB over 99 percent; Color Depth: 16.7M colors. On Screen Control with Screen Split 2.0. Black Stabilizer. Dimensions Without Stand (WxHxD)-21.3 x 12.3 x 1.8 inches. Reader Mode. Viewing Angle-178 / 178. Mounting type: VESA Size (millimeter) : 75 x 75',
    stock: 11,
    stars: 4.5,
    reviews: 8,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'LG',
    images: [
      'https://i.ibb.co/Jy0Gn5P/monitor-2.jpg',
      'https://i.ibb.co/68nFntV/monitor-1.jpg',
      'https://i.ibb.co/bFwX4d6/alienware-Hpaq-k-Bc-YHk-unsplash.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  //TODO MOUSE
  {
    name: 'LOGITECH Limited Mouse',
    category: 'Mouse',
    price: 4799,
    description:
      'Logitech G305 LIGHTSPEED Wireless Gaming Mouse, Hero 12K Sensor, 12,000 DPI, Lightweight, 6 Programmable Buttons, 250h Battery Life, On-Board Memory, PC/Mac - Black HERO Gaming Sensor: Next-gen HERO mouse sensor delivers up to 10x the power efficiency over other gaming mice with exceptional accuracy and responsiveness thanks to 400 IPS precision and up to 12000 DPI sensitivity LIGHTSPEED Wireless: Ultra-fast LIGHTSPEED Wireless technology gives you a lag-free gam experience. The G305 wireless gaming mouse delivers incredible responsiveness and reliability wit super-fast 1ms report rate for competition-level performance',
    stock: 4,
    stars: 4.8,
    reviews: 7,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Logitech',
    images: [
      'https://i.ibb.co/0hQL4Vy/frankie-Vghb-BAYq-UJ0-unsplash.jpg',
      'https://i.ibb.co/Jj24ZHq/maar-gaming-f-G4-BTSKPo3w-unsplash.jpg',
      'https://i.ibb.co/Rb7D5ZM/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'LOGITECH Wireless Mouse',
    category: 'Mouse',
    price: 3799,
    description:
      'Logitech G305 LIGHTSPEED Wireless Gaming Mouse, Hero 12K Sensor, 12,000 DPI, Lightweight, 6 Programmable Buttons, 250h Battery Life, On-Board Memory, PC/Mac - Black HERO Gaming Sensor: Next-gen HERO mouse sensor delivers up to 10x the power efficiency over other gaming mice with exceptional accuracy and responsiveness thanks to 400 IPS precision and up to 12000 DPI sensitivity LIGHTSPEED Wireless: Ultra-fast LIGHTSPEED Wireless technology gives you a lag-free gam experience. The G305 wireless gaming mouse delivers incredible responsiveness and reliability wit super-fast 1ms report rate for competition-level performance',
    stock: 22,
    stars: 4.7,
    reviews: 18,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Logitech',
    images: [
      'https://i.ibb.co/Jz78fC0/auguras-pipiras-d62p4l-EN4-R0-unsplash.jpg',
      'https://i.ibb.co/pyxCg0b/antonio-manaligod-T-2-UFB-xwzw-unsplash.jpg',
      'https://i.ibb.co/Rb7D5ZM/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Apple Magic Wireless Mouse',
    category: 'Mouse',
    price: 7999,
    description:
      'Magic Mouse is wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages  scrolling through documents. The incredibly long-lasting internal battery will power your Magic Mouse for about a month or m between charges. Its ready to go right out of the box and pairs automatically with your Mac, and it includes a wo USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac. System Requirements: Bluetooth-enabled Mac with OS X 10.11 or later , iPad with iPadOS 13.4 later',
    stock: 3,
    stars: 4.7,
    reviews: 18,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Logitech',
    images: [
      'https://i.ibb.co/Jy1cWf0/anthony-choren-e7d-G26-YCr-ZU-unsplash.jpg',
      'https://i.ibb.co/YftsX45/apple-mouse.jpg',
      'https://i.ibb.co/Rb7D5ZM/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Caurus Gaming Mouse',
    category: 'Mouse',
    price: 3999,
    description:
      'Plug & Play: Wireless mouse comes with a tiny USB Nano receiver (stored within the back of the mouse), plug it into your PC, and then forget it. With 5 adjustable DPI levels (2600-2000-1600-1200-800), you can freely choose your cursor speed. 2.4GHz Computer Mouse: Ensures reliable connection with an increased working distance of up to  (50ft) and eliminates delays, dropouts, and interference. An ergonomic mouse with a contoured sh and soft rubber grip ensure all-day comfort.',
    stock: 19,
    stars: 4.5,
    reviews: 7,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db', '#EB1D36'],
    company: 'Caurus',
    images: [
      'https://i.ibb.co/ZHh4NmN/ahmed-helal-t1-Cfe-IOl-GRk-unsplash.jpg',
      'https://i.ibb.co/0nvvZbB/d-a-v-i-d-s-o-n-l-u-n-a-m9-Bpc-OG4vus-unsplash.jpg',
      'https://i.ibb.co/Rb7D5ZM/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'ROCCAT Ergonomic Mouse',
    category: 'Mouse',
    price: 4995,
    description:
      'ROCCAT Kone Pro PC Gaming Mouse, Lightweight Ergonomic Design, Titan Switch Optical, AIMO RGB Lighting, Superlight Wired Computer Mouse, Titan Scroll Wheel, Honeycomb Shell, 19K DPI, Black AN ICONIC SHAPE, PERFECTED - Refined to perfection over hours of anthropometric research, the Kone Pros ergonomic shape and light weight of 66g offers superior comfort for any hand size or grip style',
    stock: 28,
    stars: 4.6,
    reviews: 2,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'ROCCAT',
    images: [
      'https://i.ibb.co/3RLcRHX/mohammadreza-alidoost-Fcb-VHv3c-D9o-unsplash.jpg',
      'https://i.ibb.co/74rzzV7/nubelson-fernandes-hl-Qi9-J-ai3-A-unsplash.jpg',
      'https://i.ibb.co/Rb7D5ZM/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  //TODO KEYBOARD
  {
    name: 'Keychron 87 Keys Mechanical Keyboard Red Switch',
    category: 'Keyboards',
    price: 7499,
    description:
      'Keychron C1 TKL Mechanical Keyboard USB Wired, Tenkeyless 87 Keys RGB Backlit Illuminated Keyboard, Hot-Swappable Gateron G Pro Brown Switch Double-Shot Keycaps Computer Keyboard for Windows Mac. Compatible for both macOS and Windows. With a unique Mac layout, the C1 has all the necessary Mac multimedia keys while still being compatible with Windows. Extra keycaps for both Windows and Mac operating systems are included.',
    stock: 12,
    stars: 5,
    reviews: 27,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db', '#EB1D36'],
    company: 'Keychron',
    images: [
      'https://i.ibb.co/cLn1sqs/bryan-natanael-c4a-0kyc-TUE-unsplash.jpg',
      'https://i.ibb.co/XjLz0Cw/bryan-natanael-V-Zg-V8-Uu-L3-M-unsplash.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Keychron 87 Keys Mechanical Keyboard Blue Switch',
    category: 'Keyboards',
    price: 7499,
    description:
      'Keychron C1 TKL Mechanical Keyboard USB Wired, Tenkeyless 87 Keys RGB Backlit Illuminated Keyboard, Hot-Swappable Gateron G Pro Brown Switch Double-Shot Keycaps Computer Keyboard for Windows Mac. Compatible for both macOS and Windows. With a unique Mac layout, the C1 has all the necessary Mac multimedia keys while still being compatible with Windows. Extra keycaps for both Windows and Mac operating systems are included.',
    stock: 12,
    stars: 5,
    reviews: 27,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db', '#EB1D36'],
    company: 'Keychron',
    images: [
      'https://i.ibb.co/LNKwd81/stefen-tan-KYw1e-Ux1-J7-Y-unsplash.jpg',
      'https://i.ibb.co/XjLz0Cw/bryan-natanael-V-Zg-V8-Uu-L3-M-unsplash.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Keychron 87 Keys Mechanical Keyboard Brown Switch',
    category: 'Keyboards',
    price: 7499,
    description:
      'Keychron C1 TKL Mechanical Keyboard USB Wired, Tenkeyless 87 Keys RGB Backlit Illuminated Keyboard, Hot-Swappable Gateron G Pro Brown Switch Double-Shot Keycaps Computer Keyboard for Windows Mac. Compatible for both macOS and Windows. With a unique Mac layout, the C1 has all the necessary Mac multimedia keys while still being compatible with Windows. Extra keycaps for both Windows and Mac operating systems are included.',
    stock: 12,
    stars: 4.9,
    reviews: 27,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db', '#EB1D36'],
    company: 'Keychron',
    images: [
      'https://i.ibb.co/XjLz0Cw/bryan-natanael-V-Zg-V8-Uu-L3-M-unsplash.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/LNKwd81/stefen-tan-KYw1e-Ux1-J7-Y-unsplash.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'COSTOM 87 Keys Mechanical Keyboard Yellow Switch',
    category: 'Keyboards',
    price: 8999,
    description:
      'COSTOM XVX M84 Hot Swappable Wireless Mechanical Keyboard, 75% Layout TKL Gaming Keyboard, N-Key Rollover RGB Backlit Custom Keyboard for Windows Mac PC Gamers(Izakaya Theme, Gateron Yellow Switch)The keyboard itself comes with 19 RGB backlight modes, 9 colors selection. And you can create 1 customized backlight as you like.You also expand your options using the available software to design your own new modes and effects. Macros with different keybindings or shortcuts for more efficient work and gaming.',
    stock: 4,
    stars: 5,
    reviews: 6,
    id: 'sf5sd4f5s454sdf',
    colors: ['#b18ed6', '#EB1D36', '#EE6983', '#42855B', '#277BC0'],
    company: 'COSTOM',
    images: [
      'https://i.ibb.co/vZG9k76/girl-with-red-hat-Z6-SXt1v5t-P8-unsplash.jpg',
      'https://i.ibb.co/k0P3skV/pexels-pablo-punk-10133432.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'COSTOM 87 Keys Mechanical Keyboard Red Switch',
    category: 'Keyboards',
    price: 7999,
    description:
      'COSTOM XVX M84 Hot Swappable Wireless Mechanical Keyboard, 75% Layout TKL Gaming Keyboard, N-Key Rollover RGB Backlit Custom Keyboard for Windows Mac PC Gamers(Izakaya Theme, Gateron Yellow Switch)The keyboard itself comes with 19 RGB backlight modes, 9 colors selection. And you can create 1 customized backlight as you like.You also expand your options using the available software to design your own new modes and effects. Macros with different keybindings or shortcuts for more efficient work and gaming.',
    stock: 5,
    stars: 5,
    reviews: 2,
    id: 'sf5sd4f5s454sdf',
    colors: ['#b18ed6', '#EB1D36', '#EE6983', '#42855B'],
    company: 'COSTOM',
    images: [
      'https://i.ibb.co/rs3k8NP/paul-esch-laurent-8ss-NFn4-VPLg-unsplash.jpg',
      'https://i.ibb.co/QDrC2JJ/pexels-fox-3829226.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'COSTOM 87 Keys Mechanical Keyboard Brown Switch',
    category: 'Keyboards',
    price: 7999,
    description:
      'COSTOM XVX M84 Hot Swappable Wireless Mechanical Keyboard, 75% Layout TKL Gaming Keyboard, N-Key Rollover RGB Backlit Custom Keyboard for Windows Mac PC Gamers(Izakaya Theme, Gateron Yellow Switch)The keyboard itself comes with 19 RGB backlight modes, 9 colors selection. And you can create 1 customized backlight as you like.You also expand your options using the available software to design your own new modes and effects. Macros with different keybindings or shortcuts for more efficient work and gaming.',
    stock: 5,
    stars: 5,
    reviews: 2,
    id: 'sf5sd4f5s454sdf',
    colors: ['#b18ed6', '#EB1D36', '#EE6983', '#42855B'],
    company: 'COSTOM',
    images: [
      'https://i.ibb.co/DpqDwBQ/pexels-kamil-zubrzycki-13094372.jpg',
      'https://i.ibb.co/hdqF7kq/soap-7-Ni-MV9-X7-I7k-unsplash.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'COSTOM 87 Keys Mechanical Keyboard Blue Switch',
    category: 'Keyboards',
    price: 7999,
    description:
      'COSTOM XVX M84 Hot Swappable Wireless Mechanical Keyboard, 75% Layout TKL Gaming Keyboard, N-Key Rollover RGB Backlit Custom Keyboard for Windows Mac PC Gamers(Izakaya Theme, Gateron Yellow Switch)The keyboard itself comes with 19 RGB backlight modes, 9 colors selection. And you can create 1 customized backlight as you like.You also expand your options using the available software to design your own new modes and effects. Macros with different keybindings or shortcuts for more efficient work and gaming.',
    stock: 2,
    stars: 5,
    reviews: 1,
    id: 'sf5sd4f5s454sdf',
    colors: ['#277BC0', '#FEDB39'],
    company: 'COSTOM',
    images: [
      'https://i.ibb.co/drX6PWY/kishore-v-Dq-BL4-Agtr6-E-unsplash.jpg',
      'https://i.ibb.co/B6NQmTH/jay-zhang-ZRo-C-96-HPnw-unsplash.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Apple Magic Keyboard',
    category: 'Keyboards',
    price: 9999,
    description:
      'Apple Magic Keyboard - US English, Includes USB-C to Lighting Cable, White Magic Keyboard delivers a remarkably comfortable and precise typing experience. Its also wireless and rechargeable, with an incredibly long-lasting internal battery that w. power your keyboard for about a month or more between charges. It pairs automatically with your Mac, so you can get to work right away. And it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting t. USB-C port on your Mac.. System Requirements: Mac with macOS 11.3 or later, iPad with iPadOS 14.5 or later, iPhone and i. touch with iOS 14.5 or later',
    stock: 10,
    stars: 4.8,
    reviews: 4,
    id: 'sf5sd4f5s454sdf',
    colors: ['#d1d5db'],
    company: 'Apple',
    images: [
      'https://i.ibb.co/f9NH9xt/clay-banks-PXa-QXTh-G1-FY-unsplash.jpg',
      'https://i.ibb.co/YftsX45/apple-mouse.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Logitech Ergonomic Keyboard',
    category: 'Keyboards',
    price: 5999,
    description:
      'Wave design with Constant Curve layout: Curved layout guides hands into just the right position Ease and comfort: Cushioned palm rest makes work easier and fun more fun Longer battery time: This feature gives you up to three years of battery life. (Battery life ba on a calculation of an estimated 2 million keystrokes per year in an office environment. U experience may vary.) Logitech Unifying receiver: The tiny Unifying receiver stays in your notebook, so theres no need unplug it when you move around. And you can easily add compatible wireless mice and keyboards to  same wireless receiver',
    stock: 10,
    stars: 4.9,
    reviews: 3,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Logitech',
    images: [
      'https://i.ibb.co/dKbtdYk/pexels-liam-wheelden-238582.jpg',
      'https://i.ibb.co/VSxGM7L/logitech.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Vision Ergonomic Split Keyboard',
    category: 'Keyboards',
    price: 8999,
    description:
      'Wave design with Constant Curve layout: Curved layout guides hands into just the right position Ease and comfort: Cushioned palm rest makes work easier and fun more fun Longer battery time: This feature gives you up to three years of battery life. (Battery life ba on a calculation of an estimated 2 million keystrokes per year in an office environment. U experience may vary.) Logitech Unifying receiver: The tiny Unifying receiver stays in your notebook, so theres no need unplug it when you move around. And you can easily add compatible wireless mice and keyboards to  same wireless receiver',
    stock: 3,
    stars: 0,
    reviews: 0,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#d1d5db'],
    company: 'Vision',
    images: [
      'https://i.ibb.co/NFfdfwp/split-vision-1.jpg',
      'https://i.ibb.co/wKRyDMF/split-vision-2.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Red Dragon Mechanical 61keys Keyboard Red Switch',
    category: 'Keyboards',
    price: 4499,
    description:
      'Redragon K617 Fizz 60% Wired RGB Gaming Keyboard, 61 Keys Compact Mechanical Keyboard w/White and Grey Color Keycaps, Linear Red Switch, Pro Driver/Software Supported Slim Fresh K617: Redragons new 60% layout wired keyboard in a refreshing style with a no-brainer deal economic offer. Compact 61 keys with selected keycaps, dedicated for FPS Gamers and efficient working. Hot-Swappable Red Switches: Most quiet mechanical switch, linear and soft key travel makes every click easy to register. Hot-swappable with other Redragon switches. Made to last with switches rated for 50 million keypresses.',
    stock: 30,
    stars: 4.4,
    reviews: 33,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000', '#277BC0', '#FEDB39'],
    company: 'Red Dragon',
    images: [
      'https://i.ibb.co/Vx51tW8/reddragon.jpg',
      'https://i.ibb.co/st74y0t/reddragon2.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
  {
    name: 'Red Dragon Mechanical 87keys Keyboard Red Switch',
    category: 'Keyboards',
    price: 3299,
    description:
      'Redragon K617 Fizz 60% Wired RGB Gaming Keyboard, 87 Keys Compact Mechanical Keyboard w/White and Grey Color Keycaps, Linear Red Switch, Pro Driver/Software Supported Slim Fresh K617: Redragons new 60% layout wired keyboard in a refreshing style with a no-brainer deal economic offer. Compact 61 keys with selected keycaps, dedicated for FPS Gamers and efficient working. Hot-Swappable Red Switches: Most quiet mechanical switch, linear and soft key travel makes every click easy to register. Hot-swappable with other Redragon switches. Made to last with switches rated for 50 million keypresses.',
    stock: 20,
    stars: 4.5,
    reviews: 50,
    id: 'sf5sd4f5s454sdf',
    colors: ['#000'],
    company: 'Red Dragon',
    images: [
      'https://i.ibb.co/smc6tSM/reddragon3.jpg',
      'https://i.ibb.co/1rF2VdG/71mj0h5-Jgy-L-AC-SL1500.jpg',
      'https://i.ibb.co/sQ6Mw6x/random.jpg',
      'https://i.ibb.co/2vX8Zhq/random-gadgets.jpg',
      'https://i.ibb.co/vsgj8N3/package.jpg',
    ],
  },
];
